export type TransferType = 'FILE' | 'TEXT';

export interface TransferFile {
  id: string;
  type: TransferType;
  file?: File;      // Present if type is FILE
  message?: string; // Present if type is TEXT
  code: string;
  maxDownloads: number;
  currentDownloads: number;
  expiresAt?: number;
  aiDescription?: string; // Generated by Gemini
}

export interface UploadConfig {
  maxDownloads: number;
}

export enum AppMode {
  UPLOAD = 'UPLOAD',
  RETRIEVE = 'RETRIEVE'
}